### ISSUE TITLE
Empresas sem link para vagas

### ISSUE THREAD

**Issue by danielhe4rt** [DanielHe4rt/empresas-php#69]
Olá! Vi recentemente que foram aprovados vários PR's dentro do projeto incluindo empresas que não tem acesso à areas de vagas. 

Minha ideia inicial era trazer apenas empresas que fossem de fácil acesso para vagas, independente da senioridade... Existe alguma sugestão para arrumarmos isso?

**Comment by gustavofreze** [comment]
Algumas empresas não possuem a área de carreiras, e só recebem a aplicação pelo Linkedin. É esse tipo de situação, que você está questionando?

**Comment by gustavofreze** [comment]
> Olá! Vi recentemente que foram aprovados vários PR's dentro do projeto incluindo empresas que não tem acesso à areas de vagas.
> 
> Minha ideia inicial era trazer apenas empresas que fossem de fácil acesso para vagas, independente da senioridade... Existe alguma sugestão para arrumarmos isso?

Algumas empresas não possuem a área de carreiras, e só recebem a aplicação pelo Linkedin. É esse tipo de situação, que você está questionando?

**Comment by danielhe4rt** [comment]
Sim. A ideia é colocar um lugar especifico pra buscar as vagas. 

Creio que as vagas do LinkedIn ou até msm um link pra um search dos caras já resolveria... O que você acha @NicolasPereira ?
